# -*- coding: utf-8 -*-
"""Seaborn(Dist,_kde,_pair_and_joints_plots.ipynb)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_fu3RSGJetPTkv729jQuzxU-sdpil_MX

## Importing Libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

# %matplotlib inline

# Problem 1: Plot a rugplot on given below random generated data.
num = np.random.randn(170)

sns.distplot(num,rug = True)

# Problem 2: Plot a pairs plot on iris data set showing different species. Write your conclusions as well.
iris = sns.load_dataset('iris')
iris.head()

sns.pairplot(iris,hue='species')

"""petal_length vs petal_width helps to draw a conclusion on the identification of of the flowers. area denoted by (0<=petal_length<=2) and (0<=petal_width<=0.6) indicates setosa

area denoted by (2.5<=petal_lenght<=5) and (1<=petal_width<=1.7) indicates versicolor

area denoted by (5< petal_lenght<=5) and (2<=petal_width) indicates virginica
"""



"""### Problem 3: Plot a joint plot showing relation between 'petal length' and 'petal width' with density estimates."""

sns.jointplot(data=iris,x='petal_length',y='petal_width',kind='kde')

# Problem 4: Plot a pie chart of survived based on sex.
titanic=sns.load_dataset('titanic')
titanic.head()

(titanic[titanic['alive']=='yes']['sex']).value_counts().plot(kind='pie',autopct='%0.1f%%')
plt.show()





























