# -*- coding: utf-8 -*-
"""Seaborn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrIq7Mz_d4j07X9wNr__3cHtVQXY_k_i
"""

import seaborn as sns
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount("/content/drive")

data=sns.load_dataset("titanic")

data.head()

data.tail()

"""### **Problem 1 : Plot a Heatmap on the correlation between multiple columns**"""

sns.heatmap(data.corr(),cbar=False,linewidths=0.5,annot = True,linecolor='black',cmap='summer',fmt='0.4f')

"""### **Problem 2 : Plot the distribution of age column using a Boxplot on the basis of sex column**"""

sns.boxplot(x='sex',y='age',data=data)

"""**Problem 3 : Plot the distribution of age using a ViolinPlot on the basis of both Pclass and Sex column**"""

sns.violinplot(x='pclass',y='age',hue='sex',split=True,data=data)

"""### **Problem 4 : Plot the count of Survivors and Non-Survivors**"""

sns.catplot(x='alive',kind='count',data=data)

"""### **Problem 5: Plot the count of survivors as well as non-survivors on the basis of Pclass**"""

sns.catplot(x='alive',hue='pclass',kind='count', data=data)

"""### **Problem 6: Plot a scatterplot between age and fare column on the basis of both Pclass and Sex column**

## **Solution:1**
"""

sns.relplot(x='age',y='fare',hue='sex',style='pclass',data=data)

"""## **Solution:2**"""

sns.relplot(x='age',y='fare',size='pclass',hue='sex',sizes=(50,200),data=data)





